# Generated by Django 2.2.2 on 2019-06-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('title_en', models.TextField()),
                ('audience', models.IntegerField()),
                ('open_date', models.DateTimeField()),
                ('genre', models.TextField()),
                ('watch_grade', models.TextField()),
                ('score', models.FloatField()),
                ('poster_url', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
