# Generated by Django 2.2.2 on 2019-06-11 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='movie_id',
            new_name='movie',
        ),
    ]
